name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: node:22-alpine

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hemanth0921/gog:1.0
    - name: Push the Docker image
      run: docker login -u hemanth0921 -p ${{ secrets.DOCKER_TOKEN }} && docker push hemanth0921/gog:1.0 
